# we need trusty for the chrome addon
dist: trusty

# we don't need sudo, so can run in a container, which makes startup much
# quicker.
#
# unfortunately we do temporarily require sudo as a workaround for
# https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

language: node_js
node_js:
    - node # Latest stable version of nodejs.
addons:
    chrome: stable
install:
    - npm install
# install synapse prerequisites for end to end tests
    - sudo apt-get install build-essential python2.7-dev libffi-dev python-pip python-setuptools sqlite3 libssl-dev python-virtualenv libjpeg-dev libxslt1-dev
script:
    ./scripts/travis.sh
