language: node_js
node_js:
    - node # Latest stable version of nodejs.
install:
    - npm install
    - (cd node_modules/matrix-js-sdk && npm install)
script:
    # don't run the riot tests unless the react-sdk tests pass, otherwise
    # the output is confusing.
    - npm run test && ./.travis-test-riot.sh
