steps:
  - label: ":eslint: JS Lint"
    command:
      - "echo '--- Install js-sdk'"
      - "./scripts/ci/install-deps.sh"
      - "yarn lint:js"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":eslint: TS Lint"
    command:
      - "echo '--- Install js-sdk'"
      - "./scripts/ci/install-deps.sh"
      - "yarn lint:ts"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":eslint: Types Lint"
    command:
      - "echo '--- Install js-sdk'"
      - "./scripts/ci/install-deps.sh"
      - "yarn lint:types"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":jest: Tests"
    agents:
      # We use a medium sized instance instead of the normal small ones because
      # webpack loves to gorge itself on resources.
      queue: "medium"
    command:
      - "echo '--- Install js-sdk'"
      # TODO: Remove hacky chmod for BuildKite
      - "chmod +x ./scripts/ci/*.sh"
      - "chmod +x ./scripts/*"
      - "echo '--- Installing Dependencies'"
      - "./scripts/ci/install-deps.sh"
      - "echo '--- Running initial build steps'"
      - "yarn build"
      - "echo '+++ Running Tests'"
      - "yarn test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: "🛠 Build"
    command:
      - "echo '--- Install js-sdk'"
      - "./scripts/ci/install-deps.sh"
      - "echo '+++ Building Project'"
      - "yarn build"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":chains: End-to-End Tests"
    agents:
      # We use a xlarge sized instance instead of the normal small ones because
      # e2e tests otherwise take +-8min
      queue: "xlarge"
    command:
      # TODO: Remove hacky chmod for BuildKite
      - "echo '--- Setup'"
      - "chmod +x ./scripts/ci/*.sh"
      - "chmod +x ./scripts/*"
      - "echo '--- Install js-sdk'"
      - "./scripts/ci/install-deps.sh"
      - "echo '--- Running initial build steps'"
      - "yarn build"
      - "echo '+++ Running Tests'"
      - "./scripts/ci/end-to-end-tests.sh"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/riotweb-ci-e2etests-env:latest"
          propagate-environment: true
          workdir: "/workdir/matrix-react-sdk"
    retry:
      automatic:
        - exit_status: 1 # retry end-to-end tests once as Puppeteer sometimes fails
          limit: 1

  - label: "🔧 Element Tests"
    agents:
      # We use a medium sized instance instead of the normal small ones because
      # webpack loves to gorge itself on resources.
      queue: "medium"
    command:
      # TODO: Remove hacky chmod for BuildKite
      - "chmod +x ./scripts/ci/*.sh"
      - "chmod +x ./scripts/*"
      - "echo '+++ Running Tests'"
      - "./scripts/ci/element-unit-tests.sh"
    plugins:
      - docker#v3.0.1:
          image: "node:10"
          propagate-environment: true
          workdir: "/workdir/matrix-react-sdk"

  - label: "🌐 i18n"
    command:
      - "echo '--- Fetching Dependencies'"
      - "yarn install"
      - "echo '+++ Testing i18n output'"
      - "yarn diff-i18n"
    plugins:
      - docker#v3.0.1:
          image: "node:10"

  - wait

  - label: "🐴 Trigger element-web"
    trigger: "element-web"
    branches: "develop"
    build:
        branch: "develop"
        message: "[react-sdk] ${BUILDKITE_MESSAGE}"
    async: true
