name: Develop jobs
on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]
jobs:
    end-to-end:
        runs-on: ubuntu-latest
        container: vectorim/element-web-ci-e2etests-env:latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: End-to-End tests
              run: ./scripts/ci/end-to-end-tests.sh
            - name: Archive logs
              uses: actions/upload-artifact@v2
              with:
                path: |
                    test/end-to-end-tests/logs/**/*
                    test/end-to-end-tests/synapse/installations/consent/homeserver.log
                retention-days: 14
            - name: Archive performance benchmark
              uses: actions/upload-artifact@v2
              with:
                name: performance-entries.json
                path: test/end-to-end-tests/performance-entries.json
