# Produce a build of element-web with this version of react-sdk
# and any matching branches of element-web and js-sdk, output it
# as an artifact and run integration tests.
name: Element Web - Build
on:
    schedule:
        - cron: "17 4 * * 1-5" # every weekday at 04:17 UTC
    pull_request: {}
    merge_group:
        types: [checks_requested]
    push:
        branches: [develop, master]
    repository_dispatch:
        types: [upstream-sdk-notify]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true
env:
    # These must be set for fetchdep.sh to get the right branch
    REPOSITORY: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
    build:
        name: "Build Element-Web"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            - name: Fetch layered build
              id: layered_build
              run: |
                  scripts/ci/layered.sh
                  JSSDK_SHA=$(git -C matrix-js-sdk rev-parse --short=12 HEAD)
                  REACT_SHA=$(git rev-parse --short=12 HEAD)
                  VECTOR_SHA=$(git -C element-web rev-parse --short=12 HEAD)
                  echo "VERSION=$VECTOR_SHA-react-$REACT_SHA-js-$JSSDK_SHA" >> $GITHUB_OUTPUT

            - name: Copy config
              run: cp element.io/develop/config.json config.json
              working-directory: ./element-web

            # After building we write the version file and the react-sdk sha so our cypress tests are from the same sha
            - name: Build
              env:
                  CI_PACKAGE: true
                  VERSION: "${{ steps.layered_build.outputs.VERSION }}"
              run: |
                  yarn build
                  echo $VERSION > webapp/version
                  echo $GITHUB_SHA > webapp/sha
              working-directory: ./element-web

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: previewbuild
                  path: element-web/webapp
                  # We'll only use this in a triggered job, then we're done with it
                  retention-days: 1
