# Produce a build of element-web with this version of react-sdk
# and any matching branches of element-web and js-sdk, output it
# as an artifact and run integration tests.
name: Element Web - Build and Test
on:
  pull_request: { }
  push:
    branches: [ develop, master ]
  repository_dispatch:
    types: [ upstream-sdk-notify ]
jobs:
  build:
    name: "Build Element-Web"
    runs-on: ubuntu-latest
    env:
      # This must be set for fetchdep.sh to get the right branch
      PR_NUMBER: ${{github.event.number}}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Fetch layered build
        run: scripts/ci/layered.sh

      - name: Copy config
        run: cp element.io/develop/config.json config.json
        working-directory: ./element-web

      - name: Build
        run: CI_PACKAGE=true yarn build
        working-directory: ./element-web

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: previewbuild
          path: element-web/webapp
          # We'll only use this in a triggered job, then we're done with it
          retention-days: 1

  cypress:
    name: "Cypress End to End Tests"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: previewbuild
          path: webapp

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          # The built in Electron runner seems to grind to a halt trying
          # to run the tests, so use chrome.
          browser: chrome
          start: npx serve -p 8080 webapp

      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos
            cypress/synapselogs

  netlify:
    name: "Deploy to Netlify"
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Create Deployment ID
        uses: altinukshini/deployment-action@v1.2.6
        id: deployment
        with:
          token: "${{ github.token }}"
          pr: true
          pr_id: ${{ github.event.pull_request.number }}
          transient_environment: true
          initial_status: in_progress
          ref: ${{ github.head_ref }}
          description: |
            Do you trust the author of this PR? Maybe this build will steal your keys or give you malware.
            Exercise caution. Use test accounts.

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: previewbuild
          path: webapp

      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: webapp
          deploy-message: "Deploy from GitHub Actions"
          # These don't work because we're in workflow_run
          enable-pull-request-comment: false
          enable-commit-comment: false
          alias: pr${{ github.event.pull_request.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

      - name: Update deployment status (success)
        if: success()
        uses: altinukshini/deployment-status@v1.0.1
        with:
          token: "${{ github.token }}"
          target_url: ${{ steps.netlify.outputs.deploy-url }}
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          pr: true
          pr_id: ${{ github.event.pull_request.number }}
      - name: Update deployment status (failure)
        if: failure()
        uses: altinukshini/deployment-status@v1.0.1
        with:
          token: "${{ github.token }}"
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          pr: true
          pr_id: ${{ github.event.pull_request.number }}

      - name: Edit PR Description
        uses: Beakyn/gha-comment-pull-request@2167a7aee24f9e61ce76a23039f322e49a990409
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          description-message: |
            Preview: ${{ steps.netlify.outputs.deploy-url }}
            ⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

  app-tests:
    name: Element Web Integration Tests
    runs-on: ubuntu-latest
    env:
      # This must be set for fetchdep.sh to get the right branch
      PR_NUMBER: ${{github.event.number}}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Run tests
        run: "./scripts/ci/app-tests.sh"
