name: Layered Preview Build
on:
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        env:
          PR_NUMBER: ${{github.event.number}}
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: scripts/ci/layered.sh && cd element-web && cp element.io/develop/config.json config.json && CI_PACKAGE=true yarn build
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: previewbuild
                  path: element-web/webapp
                  # We'll only use this in a triggered job, then we're done with it
                  retention-days: 1
            - uses: actions/github-script@v3.1.0
              with:
                script: |
                    var fs = require('fs');
                    fs.writeFileSync('${{github.workspace}}/pr.json', JSON.stringify(context.payload.pull_request));
            - name: Upload PR Info
              uses: actions/upload-artifact@v2
              with:
                  name: pr.json
                  path: pr.json
                  # We'll only use this in a triggered job, then we're done with it
                  retention-days: 1

