name: SonarQube
on:
  workflow_run:
    workflows: [ "Tests" ]
    types:
      - completed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  sonarqube:
    permissions:
      contents: none
    name: 🩻 SonarQube
    uses: matrix-org/matrix-js-sdk/.github/workflows/sonarcloud.yml@develop
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
