name: Upgrade Dependencies
on:
  workflow_dispatch: { }
permissions:
  contents: read

jobs:
  upgrade:
    permissions:
      contents: none
    uses: matrix-org/matrix-js-sdk/.github/workflows/upgrade_dependencies.yml@develop
    secrets:
      ELEMENT_BOT_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
